services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Svc\SitemapBundle\Sitemap\SitemapCreator:
    public: true
  Svc\SitemapBundle\Sitemap\SitemapHelper:
  Svc\SitemapBundle\Sitemap\RouteParser:
  Svc\SitemapBundle\Command\CreateSitemapCommand:


when@test:
  services:
    Svc\SitemapBundle\Sitemap\SitemapHelper:
      public: true
      autowire: true
      autoconfigure: true
