services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Svc\SitemapBundle\Sitemap\SitemapCreator:
    public: true
  Svc\SitemapBundle\Sitemap\SitemapHelper:
  Svc\SitemapBundle\Sitemap\RouteParser:
  Svc\SitemapBundle\Command\CreateSitemapCommand:
  Svc\SitemapBundle\Event\AddDynamicRoutesEvent:

  Svc\SitemapBundle\Robots\RobotsCreator:
    public: true
  Svc\SitemapBundle\Robots\RobotsHelper:
  Svc\SitemapBundle\Command\CreateRobotsTxtCommand:
  Svc\SitemapBundle\Event\AddRobotsTxtEvent:

  Svc\SitemapBundle\Service\RouteHandler:


when@test:
  services:
    Svc\SitemapBundle\Sitemap\SitemapHelper:
      public: true
      autowire: true
      autoconfigure: true
