services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Svc\SitemapBundle\Service\SitemapCreator:
    public: true
  Svc\SitemapBundle\Service\SitemapHelper:
    public: true
  Svc\SitemapBundle\Service\RouteParser:
  Svc\SitemapBundle\Command\CreateSitemapCommand:
